apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: node-ssl-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your@email.com # CHANGE TO YOUR EMAIL HERE
    privateKeySecretRef:
      name: node-ssl-prod
    http01: {}
